name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_VITE_API_KEY: ${{ secrets.API_KEY }}
          envkey_VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          envkey_VITE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          envkey_VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          envkey_VITE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          envkey_VITE_APP_ID: ${{ secrets.APP_ID }}

      - name: Build project
        run: yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: apple.choccobear.tech
